### ISSUE TITLE
update install notes

### ISSUE THREAD

**Issue by Kristoffernegendahl** [livestock3d/livestock3d#3]
Download and Install Livestock3D
Download the Livestock Grasshopper zip **here**
Create a folder at %appdata%\McNeel\Rhinoceros\5.0\scripts called livestock3d
Put the files from the folder "grasshopper" in there.
Create a folder called C:\livestock3d
Put the files from the folder livestock3d there.
Move the folder "Grasshopper Script" to a location of your choosing.
Put the files from "UserObjects" to the Grasshopper UserObjects folder.
More details about the Livestock project can be found here

**Comment by ocni-dtu** [comment]
fixed
